spring:
  application:
    name: franchise-api
  
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/franchise_db}
    username: ${SPRING_R2DBC_USERNAME:admin}
    password: ${SPRING_R2DBC_PASSWORD:password}
  
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:always}
      schema-locations: classpath:schema.sql

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method